name: Deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - name: Run build
        run: CGO_ENABLED=0 GOOS=linux go build -o app cmd/main.go
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: './deploy.Dockerfile'
          context: .
          push: true
          tags: nathanramli/solcare-backend:latest
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop solcare
            docker rm solcare
            docker rmi nathanramli/solcare-backend:latest
            docker pull nathanramli/solcare-backend:latest
            docker run -d --name solcare --env-file ~/env/prod.env -v "$(pwd)"/resources:/resources --network postgres -p 80:80 nathanramli/solcare-backend:latest
